export const emptyDashboardFilters = {
    motivo: [],
    idadePedido: [],
    cidade: "",
    bairro: "",
    nomeCliente: "",
    clienteT: [],
    operacao: [],
    setor: [],
    tipoCliente: [],
    palete: [],
    drop: [],
    soma: [],
    pedido: "",
    idade: [],
};
