import { AUTH_FORM_MODES } from "@/features/auth/types";
import { APP_ROUTES } from "@/shared/navigation/lib/appRoutes";

export const AUTH_PAGE_CONTENT = {
  login: {
    mode: AUTH_FORM_MODES.LOGIN,
    footer: "portal de acesso logimarui",
    formTitle: "Entrar na plataforma",
    formDescription:
      "Informe seu CPF e a senha atual para acessar o ambiente.",
    submitLabel: "Entrar",
    helperText:
      "Se o acesso estiver com senha provisoria, o proximo passo sera a definicao de uma nova senha antes da sessao final.",
    successPrefix: "Sessao iniciada com sucesso.",
    secondaryLink: {
      label: "Precisa de acesso ao ambiente?",
      cta: "Cadastrar usuario",
      href: APP_ROUTES.REGISTER,
    },
    auxiliaryLinks: [{ label: "Recuperar senha", href: APP_ROUTES.FORGOT_PASSWORD }],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF vinculado ao seu acesso.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true, allowTestValue: "cpf" },
      },
      {
        name: "password",
        label: "Senha",
        type: "password",
        placeholder: "Digite sua senha",
        hint: "Use a senha cadastrada para o seu perfil.",
        autoComplete: "current-password",
        required: true,
        validation: { minLength: 8, allowTestValue: "password" },
      },
    ],
  },
  register: {
    mode: AUTH_FORM_MODES.REGISTER,
    footer: "portal de acesso logimarui",
    formTitle: "Cadastrar novo usuario",
    formDescription:
      "Informe os dados basicos do usuario, incluindo o e-mail que podera ser usado no recovery de senha.",
    submitLabel: "Cadastrar",
    helperText:
      "Use este fluxo para preparar acessos de novos colaboradores ou perfis previamente autorizados, com dados suficientes para autenticacao e recovery.",
    successPrefix: "Cadastro concluido com sucesso.",
    secondaryLink: {
      label: "Ja possui acesso?",
      cta: "Voltar para login",
      href: APP_ROUTES.LOGIN,
    },
    auxiliaryLinks: [
      { label: "Esqueci minha senha", href: APP_ROUTES.FORGOT_PASSWORD },
    ],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF do usuario que sera cadastrado.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true },
      },
      {
        name: "name",
        label: "Nome completo",
        type: "text",
        placeholder: "Nome completo do usuario",
        hint: "Este nome sera usado para identificar o usuario no ambiente.",
        autoComplete: "name",
        required: true,
        validation: { minLength: 3 },
      },
      {
        name: "email",
        label: "E-mail",
        type: "email",
        placeholder: "usuario@empresa.com",
        hint: "Quando informado, permite o envio de link de redefinicao por e-mail.",
        autoComplete: "email",
        required: false,
        validation: { isEmail: true },
      },
      {
        name: "phoneNumber",
        label: "Telefone",
        type: "tel",
        placeholder: "(00) 00000-0000",
        hint: "Campo opcional para contato do usuario.",
        autoComplete: "tel",
        required: false,
      },
      {
        name: "password",
        label: "Senha",
        type: "password",
        placeholder: "Crie uma senha",
        hint: "Defina uma senha inicial com no minimo 8 caracteres.",
        autoComplete: "new-password",
        required: true,
        validation: { minLength: 8 },
      },
      {
        name: "confirmPassword",
        label: "Confirmar senha",
        type: "password",
        placeholder: "Repita a senha",
        hint: "Repita a senha para confirmar o cadastro.",
        autoComplete: "new-password",
        required: true,
        validation: { matchesField: "password" },
      },
    ],
  },
  forgotPassword: {
    mode: AUTH_FORM_MODES.FORGOT_PASSWORD,
    footer: "portal de acesso logimarui",
    formTitle: "Iniciar recovery de senha",
    formDescription:
      "Informe o CPF do usuario e escolha se o processo deve apenas abrir a solicitacao ou disparar o link por e-mail.",
    submitLabel: "Registrar recovery",
    helperText:
      "O envio por e-mail depende de um endereco ja cadastrado para o usuario. Sem isso, use apenas o registro da solicitacao.",
    successPrefix: "Solicitacao registrada com sucesso.",
    secondaryLink: {
      label: "Lembrou da senha?",
      cta: "Voltar para login",
      href: APP_ROUTES.LOGIN,
    },
    auxiliaryLinks: [{ label: "Criar conta", href: APP_ROUTES.REGISTER }],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF do colaborador que precisa redefinir a senha.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true },
      },
      {
        name: "sendEmailToken",
        label: "Enviar link por e-mail agora",
        type: "checkbox",
        hint: "Ative para usar o endpoint de envio do token por e-mail cadastrado.",
        defaultValue: false,
      },
    ],
  },
  passwordRecoveryReset: {
    mode: AUTH_FORM_MODES.PASSWORD_RECOVERY_RESET,
    footer: "portal de acesso logimarui",
    formTitle: "Definir nova senha",
    formDescription:
      "Informe a nova senha para concluir a redefinicao ou a troca obrigatoria exigida no login.",
    submitLabel: "Salvar nova senha",
    helperText:
      "Esta tela depende do token presente na URL atual. Se o link estiver incompleto ou expirado, o backend recusara a operacao.",
    successPrefix: "Senha atualizada com sucesso.",
    secondaryLink: {
      label: "Voltar sem alterar agora?",
      cta: "Ir para login",
      href: APP_ROUTES.LOGIN,
    },
    auxiliaryLinks: [{ label: "Criar conta", href: APP_ROUTES.REGISTER }],
    fields: [
      {
        name: "password",
        label: "Nova senha",
        type: "password",
        placeholder: "Digite a nova senha",
        hint: "Use uma senha com no minimo 8 caracteres.",
        autoComplete: "new-password",
        required: true,
        validation: { minLength: 8 },
      },
      {
        name: "confirmPassword",
        label: "Confirmar nova senha",
        type: "password",
        placeholder: "Repita a nova senha",
        hint: "Repita a senha para confirmar a alteracao.",
        autoComplete: "new-password",
        required: true,
        validation: { matchesField: "password" },
      },
    ],
  },
};
