import { AUTH_FORM_MODES } from "@/features/auth/types";

export const AUTH_PAGE_CONTENT = {
  login: {
    mode: AUTH_FORM_MODES.LOGIN,
    footer: "portal de acesso logimarui",
    formTitle: "Entrar na plataforma",
    formDescription:
      "Informe seu CPF e senha para acessar o ambiente.",
    submitLabel: "Entrar",
    helperText:
      "Em caso de indisponibilidade ou duvida de acesso, procure o time responsavel pela operacao.",
    successPrefix: "Sessao iniciada com sucesso.",
    secondaryLink: {
      label: "Precisa de acesso ao ambiente?",
      cta: "Cadastrar usuario",
      href: "/register",
    },
    auxiliaryLinks: [{ label: "Recuperar senha", href: "/forgot-password" }],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF vinculado ao seu acesso.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true, allowTestValue: "cpf" },
      },
      {
        name: "password",
        label: "Senha",
        type: "password",
        placeholder: "Digite sua senha",
        hint: "Use a senha cadastrada para o seu perfil.",
        autoComplete: "current-password",
        required: true,
        validation: { minLength: 6, allowTestValue: "password" },
      },
    ],
  },
  register: {
    mode: AUTH_FORM_MODES.REGISTER,
    footer: "portal de acesso logimarui",
    formTitle: "Cadastrar novo usuario",
    formDescription:
      "Informe o CPF, o nome do usuario e a senha inicial para liberar o acesso.",
    submitLabel: "Cadastrar",
    helperText:
      "Use este fluxo para preparar acessos de novos colaboradores ou perfis previamente autorizados.",
    successPrefix: "Cadastro concluido com sucesso.",
    secondaryLink: {
      label: "Ja possui acesso?",
      cta: "Voltar para login",
      href: "/login",
    },
    auxiliaryLinks: [
      { label: "Esqueci minha senha", href: "/forgot-password" },
    ],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF do usuario que sera cadastrado.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true },
      },
      {
        name: "username",
        label: "Nome do usuario",
        type: "text",
        placeholder: "Nome completo ou identificacao do usuario",
        hint: "Este nome sera usado para identificar o usuario no ambiente.",
        autoComplete: "name",
        required: true,
        validation: { minLength: 3 },
      },
      {
        name: "password",
        label: "Senha",
        type: "password",
        placeholder: "Crie uma senha",
        hint: "Defina uma senha inicial com no minimo 6 caracteres.",
        autoComplete: "new-password",
        required: true,
        validation: { minLength: 6 },
      },
      {
        name: "confirmPassword",
        label: "Confirmar senha",
        type: "password",
        placeholder: "Repita a senha",
        hint: "Repita a senha para confirmar o cadastro.",
        autoComplete: "new-password",
        required: true,
        validation: { matchesField: "password" },
      },
    ],
  },
  forgotPassword: {
    mode: AUTH_FORM_MODES.FORGOT_PASSWORD,
    footer: "portal de acesso logimarui",
    formTitle: "Recuperar acesso",
    formDescription:
      "Informe o CPF do usuario para registrar a solicitacao de troca de senha.",
    submitLabel: "Registrar solicitacao",
    helperText:
      "Depois do registro, a equipe pode acompanhar o status da solicitacao e orientar a proxima etapa do atendimento.",
    successPrefix: "Solicitacao registrada com sucesso.",
    secondaryLink: {
      label: "Lembrou da senha?",
      cta: "Voltar para login",
      href: "/login",
    },
    auxiliaryLinks: [{ label: "Criar conta", href: "/register" }],
    fields: [
      {
        name: "cpf",
        label: "CPF",
        type: "text",
        inputMode: "numeric",
        placeholder: "000.000.000-00",
        hint: "Informe o CPF do colaborador que precisa redefinir a senha.",
        autoComplete: "username",
        maxLength: 14,
        format: "cpf",
        required: true,
        validation: { isCpf: true },
      },
    ],
  },
};
