export const referenceFieldMap = {
    cliente: {
        clienteId: ["codigo cliente", "cliente", "cod pdv", "cod. pdv"],
        nome: ["nome cliente", "nome pdv", "nome"],
        cidade: ["cidade", "nome municipio", "nome municipio"],
        bairro: ["bairro", "rotulo"],
        tipoCliente: ["tipo cliente", "desc categoria cliente", "categoria cliente"],
        clienteT: ["cliente t", "prioridade", "prioridade tipo cliente"],
        latitude: ["latitude"],
        longitude: ["longitude"],
        setor: ["setor", "setor planner", "nome setor"],
    },
    pedido: {
        pedidoId: ["pedido"],
        data: ["data pedido", "data"],
        clienteId: ["cod pdv", "cliente", "codigo cliente"],
        clienteNome: ["nome pdv", "nome cliente", "nome"],
        cidade: ["nome municipio", "cidade"],
        roteiro: ["mapa", "nr roadshow"],
        motivo: ["motivo", "ocorrencia", "situacao", "status pedido"],
        operacao: ["desc operacao", "operacao"],
        setor: ["setor", "nome setor", "cod setor atendimento"],
        idadePedido: ["idade do pedido", "idade"],
        pesoBrutoKg: ["peso bruto", "peso bruto kg", "peso total"],
        volumeHl: ["volume marcacao", "volume pedido", "volume total"],
        quantidade: ["quantidade"],
        valor: ["total pedido", "valor", "preco unitario"],
        drop: ["fora de rota", "drop"],
        soma: ["ajuste", "soma"],
        palete: ["palete"],
    },
    produto: {
        codProduto: ["cod prod", "cod. prod.", "produto", "codigo", "codigo produto sap"],
        nomeProduto: ["nome prod", "nome produto", "descricao", "descricao unitaria"],
        categoria: ["desc tipo marca", "tipo marca", "grupo", "fam embalagem siv"],
        quantidade: ["quantidade"],
        precoUnitario: ["preco unitario"],
        pesoKg: ["peso bruto kg", "peso total"],
        volumeHl: ["volume marcacao", "volume pedido", "volume total"],
        caixasPallet: ["caixas pallet", "caixas pallet 1"],
    },
};
